version: "3"
services:
  python_linux:
    user: "${UID}:${GID}"
    build:
      context: ./docker/python_linux
    tty: true
    ports:
      - "9999:8888"
    environment:
      - PYTHONPATH=/workspace/python
    volumes:
      - ./python:/workspace/python:cached
    command: poetry run jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
  python_mac:
    user: "${UID}:${GID}"
    shm_size: "5gb"
    build:
      context: ./docker/python_mac
    tty: true
    ports:
      - "7777:8888"
    environment:
      - PYTHONPATH=/workspace/python
    volumes:
      - ./python:/workspace/python:cached
    command: poetry run jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
